#spring.mail.port=8888
#mybatis.mapper-locations=classpath:mapper/*Mapper.xml
#mybatis.type-aliases-package=com.xl.myprojectvue.pojo
#
#spring.datasource.url = jdbc:mysql://localhost:3306/my_project_vue?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#spring.datasource.username = root   //账号
#spring.datasource.password = root   //密码
#spring.datasource.driverClassName = com.mysql.jdbc.Driver
#spring.datasource.max-active=20
#spring.datasource.max-idle=8
#spring.datasource.min-idle=8
#spring.datasource.initial-size=10

spring:
  mail:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/my_project_vue?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xl.myprojectvue.pojo